#!/bin/bash

while [ "$1" != "" ] ;
do
	case $1 in
		-a|--a_option)
			echo "Letter A"
			;;
		-b|--b_option)
			echo "Letter B"
			;;
		-d|--directory)
			shift
			if [[ "$1" == "" ]] ; then
				echo "No directory specified"
				DIR=$(pwd)
				break
			elif [[ "$1" == "-"* ]] ; then
				echo "No directory specified"
				DIR=$(pwd)
				continue
			else
				echo "Setting directory"
				DIR="$1"
			fi
			;;
		--directory=?*)
			DIR=$(echo $1 | sed 's/--directory=//g')
			if [[ "$DIR" == "" ]] ; then
				echo "No directory specified"
				exit
			fi
			;;
		*)
			echo "Invalid option. See help."
			exit
			;;
	esac
	shift
done
echo "Directory: $DIR"
echo "End of script"
