#!/bin/bash

. loadcolors
location2=$(lsblk -r | awk '$4 == "1.8T" && $6 == "part" {print $1}')
location8=$(lsblk -r | awk '$4 == "7.3T" && $6 == "part" {print $1}')
location2="/dev/$location2"
location8="/dev/$location8"
mountpoint2=$(lsblk -r | awk '$4 == "1.8T" && $6 == "part" {print $7}')
mountpoint8=$(lsblk -r | awk '$4 == "7.3T" && $6 == "part" {print $7}')
echo -n "Scanning for 2TB hard drive..."
if [ "$location2" != "" ] ; then # if the drive is found
	echo -e "${LIGHTCYAN}done${NOCOLOR} | Hard drive found"
	echo -n "Mounting..."
	if [ "$mountpoint2" != "" ] ; then # if the mount point is not blank
		sudo umount -f "$location2" # so umount it
		sudo mount -t ntfs-3g -o defaults,permissions "$location2" /var/www/html/data > /dev/null 2>&1 # then mount it here
	else # if this is blank
		sudo mount -t ntfs-3g -o defaults,permissions "$location2" /var/www/html/data > /dev/null 2>&1 # so simply mount it
	fi
	newmountpoint2=$(lsblk -r | awk '$4 == "1.8T" && $6 == "part" {print $7}')
	if [ "$newmountpoint2" = "/var/www/html/data" ] ; then
		echo -e "${LIGHTCYAN}done${NOCOLOR} | Drive mounted"
	else
		echo -e "${RED}error${NOCOLOR} | Something went wrong"
	fi
	echo -n "Changing file permissions..."
	sudo chown -R www-data:www-data /var/www/html/data/data
	echo -e "${LIGHTCYAN}done${NOCOLOR}"
else # if the drive is a different size
	echo -e "${RED}error${NOCOLOR} | Drive not found"
fi
echo -n "Scanning for 8TB hard drive..."
if [ "$location8" != "" ] ; then # if the drive is found
	echo -e "${LIGHTCYAN}done${NOCOLOR} | Hard drive found"
	echo -n "Mounting..."
	if [ "$mountpoint8" != "" ] ; then # if the mount point is not blank
		sudo umount -f "$location8" # so umount it
		sudo mount "$location8" /media/server > /dev/null 2>&1 # then mount it here
	else # if this is blank
		sudo mount "$location8" /media/server > /dev/null 2>&1 # then mount it here
	fi
	newmountpoint8=$(lsblk -r | awk '$4 == "7.3T" && $6 == "part" {print $7}')
	if [ "$newmountpoint8" = "/media/server" ] ; then
		echo -e "${LIGHTCYAN}done${NOCOLOR} | Drive mounted"
	else
		echo -e "${RED}error${NOCOLOR} | Something went wrong"
	fi
else # if the drive is a different size
	echo -e "${RED}error${NOCOLOR} | Drive not found"
fi
echo -n "Initializing VNC Server..."
sleep 1
vncserver > /dev/null 2>&1
echo -e "${LIGHTCYAN}done${NOCOLOR}"
sleep 1
