#!/bin/bash

# FUNCTIONS ========================================================
# Input year and check that for 4 digits
function yearf {
	read -p "Year: " year2
	if [[ "${#year2}" = 4 ]] ; then
		year="$year2"
	else
		echo "Not a valid year. Try again.."
		sleep 1s
		yearf
	fi
}
# Takes the genre number entered, translates them into ID3 genres
# and then determines what directory this genre corresponds to
function genref {
	dir1="/media/server/music"
#	dir3="/media/server/googlemusic"
	# dir1="/home/pi/scripts/musicmanager/new_directory"
	if [[ "$genre" = "00" ]] ; then
		genre2="0"
		dir2="$dir1/blues"
	elif [[ "$genre" = "01" ]] ; then
		genre2="69"
		dir2="$dir1/broadway"
	elif [[ "$genre" = "02" ]] ; then
		genre2="12"
		dir2="$dir1/christmas"
	elif [[ "$genre" = "03" ]] ; then
		genre2="32"
		dir2="$dir1/classical"
	elif [[ "$genre" = "04" ]] ; then
		genre2="2"
		dir2="$dir1/country"
	elif [[ "$genre" = "05" ]] ; then
		genre2="52"
		dir2="$dir1/electronic"
	elif [[ "$genre" = "06" ]] ; then
		genre2="80"
		dir2="$dir1/folk"
	elif [[ "$genre" = "07" ]] ; then
		genre2="7"
		dir2="$dir1/hiphop"
	elif [[ "$genre" = "08" ]] ; then
		genre2="8"
		dir2="$dir1/jazz"
	elif [[ "$genre" = "09" ]] ; then
		genre2="13"
		dir2="$dir1/pop/80s"
	elif [[ "$genre" = "10" ]] ; then
		genre2="20"
		dir2="$dir1/pop/alternative"
	elif [[ "$genre" = "11" ]] ; then
		genre2="13"
		dir2="$dir1/pop/classic"
	elif [[ "$genre" = "12" ]] ; then
		genre2="13"
		dir2="$dir1/pop/current"
	elif [[ "$genre" = "13" ]] ; then
		genre2="14"
		dir2="$dir1/r_and_b/classic"
	elif [[ "$genre" = "14" ]] ; then
		genre2="14"
		dir2="$dir1/r_and_b/current"
	elif [[ "$genre" = "15" ]] ; then
		genre2="20"
		dir2="$dir1/rock/alternative"
	elif [[ "$genre" = "16" ]] ; then
		genre2="1"
		dir2="$dir1/rock/classic"
	elif [[ "$genre" = "17" ]] ; then
		genre2="56"
		dir2="$dir1/rock/southern"
	elif [[ "$genre" = "18" ]] ; then
		genre2="24"
		dir2="$dir1/soundtrack/disney"
	elif [[ "$genre" = "19" ]] ; then
		genre2="24"
		dir2="$dir1/soundtrack/film_score"
	elif [[ "$genre" = "20" ]] ; then
		genre2="24"
		dir2="$dir1/soundtrack/various_artist"
	fi
}
# PROGRAM STARTS HERE ===============================================
# Figure out where the tracks are located
input=$1
if [ $input = "" ] ; then
	dir=$(pwd)
else
	dir=$input
fi
input2=$2
albumshow=$(sed 's/_/ /g' <<< $input2)
if [ $input2 != "" ] ; then
echo "--------------------------------------------------------
Directory Listing for ${albumshow}
--------------------------------------------------------
"
fi
ls $dir
read -p "These are the album files to be modified. Ready to proceed? (y/n) " decide2
if [[ "$decide2" = "n" ]] ; then
	echo "Quiting.."
	exit 1
fi
# Count number of tracks
trackcount=$(ls -1 ${dir}/*.mp3 | wc -l)
echo "Found $trackcount files."
# Input artist (-a), album (-A), album artist (--TPE2 ), year (-y ####), genre (-g)
read -p "Is this a single-artist album? (y/n) " var1
if [[ "$var1" = "y" ]] ; then
	read -p "Artist: " artist
fi
read -p "Album: " album
read -p "Album Artist: " albumartist
# Use function for year to make sure the year is 4 digits
yearf
# List numbers associated with genres
read -p "Genre Number (-l for list of genres): " genre3
	if [[ "$genre3" = "-l" ]] ; then
		echo "$(</home/pi/scripts/musicmanager/genres.txt)"
		read -p "Genre Number: " genre
	else
		genre="$genre3"

	fi
# Now that we have the genre, this function will convert to ID3 genre
# and create a directory for this genre
genref
read -p "Do you want to add album art? (y/n) " albumartvar
	if [[ "$albumartvar" = "y" ]] ; then
		if [ -f ${dir}/folder.* ] ; then
			echo "Found image file."
			albumart=$(ls ${dir}/folder.*)
			sleep 1s
		else
			echo "Searching folder.."
			sleep 1s
			ls -I "${dir}/*.mp3"
			read "Type the file name of the album art, including extension (if you don't see it, type 'q') " albumartvar2
			if [ "$albumartvar2" != "q" ] ; then
				albumart=$albumartvar2
			fi
		fi
	fi
echo "Updating tracks.."
sleep 1s
# Change the values that apply to all the tracks
if [[ "$var" = "y" ]] ; then
	cd $dir && sudo id3v2 -a "$artist" -A "$album" -y $year -g $genre2 --TPE2 "$albumartist" $dir/*.mp3
	cd $dir && sudo eyeD3 --add-image "$albumart":FRONT_COVER $dir/*.mp3
else
	cd $dir && sudo id3v2 -A "$album" -y $year -g $genre2 --TPE2 "$albumartist" $dir/*.mp3
	cd $dir && sudo eyeD3 --add-image "$albumart":FRONT_COVER $dir/*.mp3
fi
echo "$trackcount tracks have been updated."
sleep 1s
# This loop will go through the tracks one by one, choose which file
# corresponds to which track number, edit the track title and track number,
# and change the file name to a reformatted one
for ((i=1;i<=trackcount;i++)) ; do
# List the tracks with numeric headers
(cd $dir && ls -1 *.mp3 | nl)
# Select tracks one at a time from the list
read -p "Select track #$i on the album (use the line number): " num
# The line number selected will assign the file to the variable track
track=$(ls -1 $dir/*.mp3 | head -n $num | tail -n 1)
# Enter the title name
read -p "Track title: " title
# Edit the title (-t), track number and total track (-T #/#)
if [[ "$var1" = "y" ]] ; then
	cd $dir && sudo id3v2 -t "$title" -T $i/$trackcount "$track"
else
	read -p "Track artist: " artist2
	cd $dir && sudo id3v2 -a "$artist2" -t "$title" -T $i/$trackcount "$track"
fi
# Now to rename the files
# First convert the title to lower case
titlelc="${title,,}"
# Second remove the spaces from the title and replace them with hyphens
titlenew="${titlelc// /-}"
# If the track number is less than 10, we need to add a 0 to it
if [[ $i -lt 10 ]] ; then
	sudo mv "$track" 0$i\_"$titlenew".mp3
else
	sudo mv "$track" $i\_"$titlenew".mp3
fi
echo "Track #$i has been updated."
sleep 1s
done
# Copying albums takes a second so this lets us know whats happening
echo "Moving files.."
# Now we need to move the files into the appropriate directory
# First we're going to reformat the artist, album artist and album values
artistlc="${artist,,}"
artistnew="${artistlc// /_}" # artists are lower case and underscored
albumartistlc="${albumartist,,}"
albumartistnew="${albumartistlc// /_}" # album artists are the same
albumlc="${album,,}"
albumus="${albumlc// /_}"
albumnew=$albumus\_$year # albums are lower case, underscored with the year
# For certain directories, the directories are sorted by artist, then album
if [[ "$genre" = "00" || "$genre" = "02" || "$genre" = "03" || "$genre" = "04" || "$genre" = "05" || "$genre" = "06" || "$genre" = "07" || "$genre" = "08" || "$genre" = "09" || "$genre" = "10" || "$genre" = "11" || "$genre" = "12" || "$genre" = "13" || "$genre" = "14" || "$genre" = "15" || "$genre" = "16" || "$genre" = "17" ]] ; then
	if [[ "$var1" = "y" ]] ; then
		sudo mkdir -p "$dir2"/"$artistnew"/"$albumnew"
#		sudo mkdir -p "$dir3"/"$artistnew"/"$albumnew"
		sudo cp "$dir"/*.mp3 "$dir2"/"$artistnew"/"$albumnew"/
#		sudo cp *.mp3 "$dir3"/"$artistnew"/"$albumnew"/
		sudo rm "$dir"/*.mp3
		echo "The files have been moved."
		sleep 1s
# If the album has multiple artists we need to use the album artist for the dir
	else
		sudo mkdir -p "$dir2"/"$albumartistnew"/"$albumnew"
#		sudo mkdir -p "$dir3"/"$albumartistnew"/"$albumnew"
		sudo cp "$dir"/*.mp3 "$dir2"/"$albumartistnew"/"$albumnew"/
#		sudo cp *.mp3 "$dir3"/"$albumartistnew"/"$albumnew"/
		sudo rm "$dir"/*.mp3
		echo "The files have been moved."
		sleep 1s
	fi
# For these directories, the directories are sorted just by album
elif [[ "$genre" = "18" || "$genre" = "19" || "$genre" = "20" ]] ; then
	sudo mkdir -p "$dir2"/"$albumnew"
#	sudo mkdir -p "$dir3"/"$albumnew"
	sudo cp "$dir"/*.mp3 "$dir2"/"$albumnew"/
#	sudo cp *.mp3 "$dir3"/"$albumnew"/
	sudo rm "$dir"/*.mp3
	echo "The files have been moved."
	sleep 1s
elif [[ "$genre" = "01" ]] ; then
	albumdash="${albumlc// /-}"
	albummin="${albumdash%-(*}"
	if [[ "$albumdash" == *"original-broadway"* ]] ; then
		albumnew2=$albummin\_$year\_obc
		sudo mkdir -p "$dir2"/"$albumnew2"
#		sudo mkdir -p "$dir3"/"$albumnew2"
		sudo cp "$dir"/*.mp3 "$dir2"/"$albumnew2"
#		sudo cp *.mp3 "$dir3"/"$albumnew2"
		sudo rm "$dir"/*.mp3
	elif [[ "$albumdash" == *"revival-broadway"* ]] ; then
		albumnew2=$albummin\_$year\_rbc
		sudo mkdir -p "$dir2"/"$albumnew2"
#		sudo mkdir -p "$dir3"/"$albumnew2"
#		sudo cp *.mp3 "$dir3"/"$albumnew2"
		sudo cp "$dir"/*.mp3 "$dir2"/"$albumnew2"
		sudo rm "$dir"/*.mp3
	elif [[ "$albumdash" == *"new-broadway"* ]] ; then
		albumnew2=$albummin\_$year\_nbc
#		sudo mkdir -p "$dir3"/"$albumnew2"
		sudo mkdir -p "$dir2"/"$albumnew2"
		sudo cp "$dir"/*.mp3 "$dir2"/"$albumnew2"
#		sudo cp *.mp3 "$dir3"/"$albumnew2"
		sudo rm "$dir"/*.mp3
	else
		echo "The broadway album seems to be named incorrectly. The director is being named differently.."
		albumnew2=$albummin\_$year
		sudo mkdir -p "$dir2"/"$albumnew2"
		sudo cp "$dir"/*.mp3 "$dir2"/"$albumnew2"
		sudo rm "$dir"/*.mp3
	fi
	echo "The files have been moved."
	sleep 1s
else
	echo "Something went wrong when moving the files. Quitting.."
	sleep 1s
	exit
fi
