#!/bin/bash
#=== PREPARE =================================================================
dir1="/home/pi/scripts/danflixr2/output" # name the directories
dir2="/home/pi/scripts/danflixr2/temp"
input=$1 # the file to be edited
file1="$dir1/$input" # the file variables
file2="$dir1/${input}_2"
file3="$dir1/${input}_3"
file4="$dir1/${input}_4"
sudo chmod 777 $file1 && sudo chown pi:pi $file1
#=== PRE-LOOP ================================================================
rowcount=$(cat $file1 | wc -l) # count the rows in the file
rowcount=$(($rowcount + 1)) # add 1
show1=$(cat $file1 | awk 'FNR == 1 {NF-=4; print}') # define the variables
season1=$(cat $file1 | awk 'FNR == 1 {print $(NF-2)}')
episode1=$(cat $file1 | awk 'FNR == 1 {print $(NF-0)}')
multi="n"
#=== MAIN LOOP (group episodes by season) ====================================
for i in $(seq 2 $rowcount); do # start on row 2
show2=$(cat $file1 | awk -v i=$i 'FNR == i {NF-=4; print}') # define current row variables
season2=$(cat $file1 | awk -v i=$i 'FNR == i {print $(NF-2)}')
episode2=$(cat $file1 | awk -v i=$i 'FNR == i {print $(NF-0)}')
if [ "$episode1" != "EpGuides.com." ] ; then # make sure this isn't a "did not come up on epguides" message
	episode1plus1=$((${episode1#0} + 1)) # add 1 to the current episode
	episode1plus1=$(printf %02d $episode1plus1)
fi
# Q1 : Is this the next episode? (Do show/season match and is the new episode 1 greater than the previous?)
if [ "$show2" == "$show1" ] && [ "$season2" = "$season1" ] && [ "$episode1plus1" = "$episode2" ] ; then # Q1: YES
# Q2a : Were we in the middle of a run of repeats? (Was multi set to y?)
	if [ "$multi" = "y" ] ; then # Q2a: YES
		multi="y" # keep multi as y since we are still in a sequence (determined by Q1)
	elif [ "$multi" = "n" ] ; then # Q2a: NO
		epstart=$episode1 # then we're at the first row of a sequence ; set the previous episode number as the start
		multi="y" # then set multi to y to signify a sequence
	fi
else # Q1: NO
# Q2b : Were we in the middle of a run of repeats? (Was multi set to y?)
	if [ "$multi" = "y" ] ; then # Q2b: YES
		epend=$episode1 # then we're at the end of a sequence; set the previous episode number as the end
		sudo echo "$show1 Season $season1 Episodes $epstart - $epend" >> $file2 #export the start and end episode to new file
		if [ "$episode2" = "EpGuides.com." ] ; then # if the current line is just a "did not come up on epguides" message...
			multi="skip" # set multi to skip
			skip=$(cat $file1 | awk -v i=$i 'FNR == i') # expor the previous line as it stands to a new file
			echo "$skip" >> $file2
		else
			multi="n" # change the multi to n since we are not in a repeat anymore
		fi
 	elif [ "$multi" = "n" ] ; then # Q2b: NO
		sudo echo "$show1 Season $season1 Episode $episode1" >> $file2 # so export the previous line as is
		if [ "$episode2" = "EpGuides.com." ] ; then # same thing again if the line is an "epguides" message
			multi="skip"
			skip=$(cat $file1 | awk -v i=$i 'FNR == i')
			echo "$skip" >> $file2
		else
			multi="n"
		fi
	elif [ "$multi" = "skip" ] ; then # if this is a skip line, we print nothing and move on
		multi="n"
	fi
fi
	show1=$show2 # change the variables before going through the run again
	season1=$season2
	episode1=$episode2
done
#=== SECOND LOOP (detect complete seasons) ============================================
rowcount=$(cat $file2 | wc -l)
for i in $(seq 1 $rowcount); do # this will go through the file line by line
	row=$(cat $file2 | awk -v i=$i 'NR == i') # set the row as a string
	if [[ $row == *"-"* ]] ; then # detect if there is an episode span in the row
		showorig=$(cat $file2 | awk -v i=$i 'FNR == i {NF-=6; print}') # define variables
		season=$(cat $file2 | awk -v i=$i 'FNR == i {print $(NF-4)}')
		epstart=$(cat $file2 | awk -v i=$i 'FNR == i {print $(NF-2)}')
		epend=$(cat $file2 | awk -v i=$i 'FNR == i {print $(NF-0)}')
		show=$(echo $showorig | sed 's/ //g' | sed 's/(//g' | sed 's/)//g') # manipulate the show string
		if [ ${show:0:3} = "The" ] ; then
			show=${show:3}
		fi
		if [ ${show: -2} == "US" ] || [ ${show: -2} == "UK" ] ; then
			show=$(echo $show | sed 's/.\{2\}$/_&/')
		fi
		if [ ${#show} -gt 4 ] ; then
			if [[ ${show: -4} =~ ^[0-9]+$ ]] ; then
				show=$(echo $show | sed 's/.\{4\}$/_&/')
			fi
		fi
		csvrowcount=$(cat $dir2/${show}_csv | wc -l)
		sudo rm -f $dir2/${show}_csv2
		for i in $(seq 2 $csvrowcount); do
			csvseason=$(cat $dir2/${show}_csv | awk -F',' -v i=$i 'FNR == i {print $1}')
			csvepisode=$(cat $dir2/${show}_csv | awk -F',' -v i=$i 'FNR == i {print $2}')
			if [ $csvepisode = "01" ] ; then
				lasti=$(($i - 1))
				lastrow=$(cat $dir2/${show}_csv | awk -v lasti=$lasti 'NR == lasti')
				echo "$lastrow" >> $dir2/${show}_csv2
			fi
		done
		realepend=$(cat $dir2/${show}_csv2 | awk -F',' -v season=$season '$1==season{print $2}')
		if [ "$epend" = "$realepend" ] ; then
			echo "$row COMPLETE" >> $file3
		else
			echo "$row" >> $file3
		fi
	else
		echo "$row" >> $file3
	fi
done
loop3multi="n"
rowcount=$(cat $file3 | wc -l)
for i in $(seq 1 $rowcount); do # this will go through the file line by line
	echo "POINT 1"
	fullrow=$(cat $file3 | awk -v i=$i 'NR == i')
	completecheck=$(cat $file3 | awk -v i=$i 'FNR == i {print $(NF-0)}')
	lasti=$((i - 1))
	lastcompletecheck=$(cat $file3 | awk -v lasti=$lasti 'FNR == lasti {print $(NF-0)}')
	if [ "$completecheck" = "COMPLETE" ] ; then # check if this row contains a complete season
		echo "POINT 2"
		if [ "$lastcompletecheck" = "COMPLETE" ] ; then # check if the last row was a complete row
			echo "POINT 3"
			loop3show1=$(cat $file3 | awk -v lasti=$lasti 'FNR == lasti {NF-=7; print}') # define previous row variables
			loop3season1=$(cat $file3 | awk -v lasti=$lasti 'FNR == lasti {print $(NF-5)}')
		else
			echo "POINT 4"
			if [ "$printalready" = "y" ] ; then
				echo "POINT 4a"
				continue
			else
				echo "POINT 4b"
				continue
			fi
		fi
		loop3show2=$(cat $file3 | awk -v i=$i 'FNR == i {NF-=7; print}') # define current row variables
		loop3season2=$(cat $file3 | awk -v i=$i 'FNR == i {print $(NF-5)}')
		loop3season1plus1=$((${loop3season1#0} + 1))
		loop3season1plus1=$(printf %02d $loop3season1plus1)
		if [ "$loop3show1" = "$loop3show2" ] && [ "$loop3season2" = "$loop3season1plus1" ] ; then # is this row sequential?
			echo "POINT 5"
			if [ "$loop3multi" = "y" ] ; then # ... and were we in the middle of a sequence? if we were...
				echo "POINT 6"
				loop3multi="y" # continue the sequence to the next line
			else # if we weren't in the middle of a sequence then this is the beginning of a sequence
				echo "POINT 7"
				loop3seasonstart=$loop3season1 # so the first season of this sequence is the one from the previous row
				loop3multi="y" #continue the sequence to the next line
			fi
		else # if this row is not sequential..
			echo "POINT 8"
			if [ "$loop3multi" = "y" ] ; then # were we in the middle of a sequence? if we were, we've now found the end
				echo "POINT 9"
#				so the season in the last row is the ending season of the sequence
				echo "$loop3show1 Seasons $loop3seasonstart - $loop3season1" >> $file4 # so print the following
			else # if we weren't in a sequence, then the last row stands alone
				echo "POINT 10"
				echo "$loop3show1 Season $loop3season1" >> $file4 # so print the previous line, condensing it
			fi
			loop3multi="n"
		fi
	else # if the current row does not contain complete
		echo "POINT 11"
		if [ "$loop3multi" = "y" ] ; then # check if this is the end of a run
			echo "POINT 12"
			lasti=$(($i - 1))
			loop3show1=$(cat $file3 | awk -v lasti=$lasti 'FNR == lasti {NF-=7; print}') # define previous row variables
			loop3season1=$(cat $file3 | awk -v lasti=$lasti 'FNR == lasti {print $(NF-5)}')
			echo "$loop3show1 Seasons $loop3seasonstart - $loop3season1" >> $file4 # print the season sequence
			echo "$fullrow" >> $file4
			loop3multi="n" # tell it that this is the end of a sequence
			printalready="n"
		elif [ "$loop3multi" = "n" ] && [ "$lastcompletecheck" = "COMPLETE" ] ; then
			echo "POINT 14"
			lasti=$(($i - 1))
			lastfullrowseasononly=$(cat $file3 | awk -v lasti=$lasti 'FNR == lasti {NF-=5; print}') # last full row season only
			echo "$lastfullrowseasononly" >> $file4
			echo "$fullrow" >> $file4
		else # if this is not the middle of a sequence, just print the line as is
			echo "POINT 13"
			echo "$fullrow" >> $file4 # if it doesn't, print the line as is
			printalready="y"
		fi
	fi
done
cat $file4
#sudo rm $file2 $file3 $file4
#=== CLEAN UP =========================================================================
#if [ -f $file2 ] ; then
#	sudo rm $file1
#	sudo mv $file2 $file1
#else
#	echo "FileFix error: File wasn't created" >> $file2
#	sudo mv $file1 ${file1}_copy
#	sudo mv $file2 $file1
#fi
