#!/bin/bash

dir1=$(pwd) # current directory
nameorig=$1
namenew=$2

read -p "Are you in the main directory of the show you need to rename? (y/n) " check
if [ "$check" = "n" ] ; then
	echo "Move to that directory and rerun the program..."
	exit 1
fi

dircount=$(ls -d $dir1 | wc -l) # count the season directories
for i in $(seq 01 $dircount); do # go through the seasons one by one
	season=$(ls -1 -d $dir1 | head -n $i | tail -n 1) # define the current season being edited
	dir2count=$(ls $season | wc -l) # count the episode files
	echo "$season $dir2count"
	for ep in $(seq 01 $dir2count); do
		episodeold=$(ls -1 -d $season | head -n $ep | tail -n 1) # define the current episode being edited
		episodenew=$(echo $episodeold | sed 's/$nameorig/$namenew/g') # change the name
		echo "$episodeold $episodenew"
	done
done
